Repository zotero/translators, pull requests merged in 2018-10, with the labels that each got.

#1755 Update Google Patents.js
  Google Patents.js
Labels: waiting

#1595 [EM] Don't concatenate different nodes by default
  Cairn.info.js
  Embedded Metadata.js
  RDF.js
Labels: Workshop

#1759 Add JISC Historical texts
  JISC Historical Texts.js
Labels: New Translator

#1669 New translator for Harvard Business Review
  Harvard Business Review.js
Labels: New Translator
