Repository zotero/translators, pull requests merged in 2021-06, with the labels that each got.

#2041 Remove old extraToCSL format from translators
  Crossref Unixref XML.js
  Datacite JSON.js
  Dryad Digital Repository.js
  Google Scholar.js
  JurPC.js
  NCBI Nucleotide.js
  RDF.js
  Treesearch.js
  Zenodo.js
  beck-online.js
Labels: waiting

#1803 Add Le Maitron
  Le Maitron.js
Labels: New Translator

#1819 Add translator for JETS
  JETS.js
Labels: New Translator

#1964 eMJA.js: Update for site changes, remove FW
  eMJA.js
Labels: Improvements

#2043 Add MIT Press translator
  MIT Press Books.js
Labels: New Translator
